---
##this script works on both Centos and Ubuntu
- hosts: server
  become: yes
  vars:
    driver: 390.87
    driver_url: http://us.download.nvidia.com/XFree86/Linux-x86_64/{{driver}}/NVIDIA-Linux-x86_64-{{driver}}-no-compat32.run
  tasks:
  - get_url: dest=. url={{driver_url}}
  - command: systemctl isolate multi-user.target
  - service: name=nvidia-docker state=stopped
    ignore_errors: True
  - shell: pkill nvidia-docker-plugin || true
  - name: Get Nvidia running processes
    shell: "lsof /dev/nvidia* 2>/dev/null | awk '{print $2}' | sort | egrep -v 'PID' | uniq"
    register: running_processes
  - name: Kill Nvidia running processes
    shell: "kill -9  {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"
  - shell: rmmod nvidia_uvm nvidia_drm nvidia_modeset nvidia || true
  - modprobe: name=nvidia state=absent
    ignore_errors: True
  - command: rm -rf /tmp/.X11*
  - command: bash NVIDIA-Linux-x86_64-{{driver}}-no-compat32.run -q -a --ui=none --uninstall
  - command: bash NVIDIA-Linux-x86_64-{{driver}}-no-compat32.run -q -a --ui=none
  - shell: nvidia-xconfig < /dev/null
  - service: name=nvidia-docker state=started
    ignore_errors: True
  - command: systemctl isolate graphical.target
  - command: systemctl set-default graphical.target
